### ISSUE TITLE
"ser" is not defined

### ISSUE THREAD

**Issue by davideciarrocchi** [weewStack/Python-projects#1]
data = ser.readline()
NameError: name 'ser' is not defined

**Comment by shyney7** [comment]
@weewStack 
I have a similar issue:
```shell
Closing the window and exiting the program...
Exception in Tkinter callback
Traceback (most recent call last):
  File "c:\Users\olivei_m\Documents\Projects\PMX_GroundStation_Visualizer\Serial_Com_ctrl.py", line 45, in SerialClose
    if self.ser.is_open:
       ^^^^^^^^
AttributeError: 'SerialCtrl' object has no attribute 'ser'
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\olivei_m\AppData\Local\Programs\Python\Python312\Lib\tkinter\__init__.py", line 1962, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "c:\Users\olivei_m\Documents\Projects\PMX_GroundStation_Visualizer\GUI_Master.py", line 24, in close_window
    self.serial.SerialClose()
  File "c:\Users\olivei_m\Documents\Projects\PMX_GroundStation_Visualizer\Serial_Com_ctrl.py", line 49, in SerialClose      
    self.ser.status = False
    ^^^^^^^^
AttributeError: 'SerialCtrl' object has no attribute 'ser'
```

**Comment by weewStack** [comment]
Hi Marcel,

Thank you for your email,
We can have a quick call and debug it together this weekend

let me know if you do have time

Best Regards

WeeW
